// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://afiyqeimfcsjsstfdytl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFmaXlxZWltZmNzanNzdGZkeXRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMzI2NDUsImV4cCI6MjA2OTgwODY0NX0.d01HydUBmHIQGL6SGMQyvSlyLSxp9qV-YbChl-iG0D8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});